# if run as "tmux attach", create a session if one does not already exist
new-session -n $HOST

# tmux-dotbar colorscheme (OneDarkVivid)
set -g @tmux-dotbar-bg "#20242b"
set -g @tmux-dotbar-fg "#5c6370"
set -g @tmux-dotbar-fg-current "#abb2bf"
set -g @tmux-dotbar-fg-session "#7f848e"
set -g @tmux-dotbar-fg-prefix "#c678dd"
set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-right-text " %H:%M "

run ~/.config/tmux/plugins/tmux-dotbar/dotbar.tmux
set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# sets CTRL+a to prefix and pressing again sends true CTRL+a
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

set -g mouse on
set -g focus-events on

# Allow applications inside tmux to passthrough escape sequences
set -g allow-passthrough on
# Ensure tmux attempts to use the clipboard
set -g set-clipboard on


# sets * to synchronize-panes
bind-key '*' setw synchronize-panes

# ctrl+shift+arrows resize panes
bind-key -n C-S-Up resize-pane -U 2
bind-key -n C-S-Down resize-pane -D 2
bind-key -n C-S-Left resize-pane -L 15
bind-key -n C-S-Right resize-pane -R 15
